import type { Metadata } from "next";

import { AppLayout } from "./_components/app-layout";
import { ReactQueryProvider } from "./_components/react-query-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: WithChildren) {
  return (
    <ReactQueryProvider>
      <AppLayout>{props.children}</AppLayout>
    </ReactQueryProvider>
  );
}
