import type { Metadata } from "next";

import { AppLayout } from "./_components/app-layout";
import { ReactQueryProvider } from "./_components/react-query-provider";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: WithChildren) {
  return (
    <AppLayout>
      <ReactQueryProvider>{props.children}</ReactQueryProvider>
    </AppLayout>
  );
}
