import { Brush, Compass } from "lucide-react";
import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";

import { ProfileMenu } from "./_components/profile-menu";
import Logo from "./favicon.ico";

import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: WithChildren) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <head>
        <script src="/apply-theme.js" defer />
      </head>
      <body className="bg-bg text-fg min-h-screen flex flex-col">
        <header className="p-base sticky top-0 bg-bg flex justify-between items-center">
          <section className="flex items-center gap-4 sm:gap-8">
            <Link href="/" className="flex gap-2 items-center">
              <Image src={Logo} alt="Logo" width={32} height={32} />
              <h3 className="not-sm:hidden">CharAi</h3>
            </Link>

            <nav className="flex gap-4">
              <Link href="/explore" className="flex items-center gap-2 text-lg">
                <Compass className="w-5" />
                Explore
              </Link>
              <Link href="/create" className="flex items-center gap-2 text-lg">
                <Brush className="w-5" />
                Create
              </Link>
            </nav>
          </section>

          <ProfileMenu />
        </header>

        <main className="p-base">{props.children}</main>

        <footer className="mt-auto p-base">
          <p>todo footer</p>
        </footer>
      </body>
    </html>
  );
}
