import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: React.PropsWithChildren) {
  return (
    <html lang="en" className="dark">
      <head>
        <script src="apply-theme.js" defer />
      </head>
      <body className="bg-bg text-fg">{props.children}</body>
    </html>
  );
}
