name: Code quality check

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  ci-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # install bun
      - uses: oven-sh/setup-bun@v1

      - name: Install bun dependencies
        run: bun install

      - name: Check types
        run: bun check

      - name: Check linting
        run: bun biome check

      - name: Check compile
        run: bun run build
        env:
          DB_URL: ${{ secrets.DB_URL }}
          PUBLIC_SITE_URL: ${{ secrets.PUBLIC_SITE_URL }}
          ARGON2_SECRET: ${{ secrets.ARGON2_SECRET }}
          JWT_SECRET_DECODE: ${{ secrets.JWT_SECRET_DECODE }}
          JWT_SECRET_ENCODE: ${{ secrets.JWT_SECRET_ENCODE }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          REDIS_TOKEN: ${{ secrets.REDIS_TOKEN }}
          RESEND_API: ${{ secrets.RESEND_API }}
